# Generated by Django 2.0 on 2017-12-08 17:20

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bokun_id', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('location', jsonfield.fields.JSONField()),
                ('json', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bokun_id', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('excerpt', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('photos', jsonfield.fields.JSONField()),
                ('external_id', models.CharField(max_length=1000)),
                ('json', jsonfield.fields.JSONField()),
                ('dropoff_places', models.ManyToManyField(related_name='_product_dropoff_places_+', to='bokun_wrapper.Place')),
                ('pickup_places', models.ManyToManyField(related_name='_product_pickup_places_+', to='bokun_wrapper.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bokun_id', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('json', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokun_wrapper.Vendor'),
        ),
    ]
