# Generated by Django 2.0 on 2017-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='bokun_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bokun_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
