# Generated by Django 2.0 on 2017-12-11 15:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0002_auto_20171211_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='json',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
