# Generated by Django 2.0 on 2017-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0003_auto_20171211_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dropoff_places',
            field=models.ManyToManyField(blank=True, related_name='_product_dropoff_places_+', to='bokun_wrapper.Place'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_places',
            field=models.ManyToManyField(blank=True, related_name='_product_pickup_places_+', to='bokun_wrapper.Place'),
        ),
    ]
