# Generated by Django 2.0 on 2017-12-14 14:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0004_auto_20171211_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='product',
            name='bookable_extras',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
