# Generated by Django 2.0 on 2017-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0006_auto_20171219_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='child_price_category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_price_category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='teenager_price_category_id',
            field=models.IntegerField(null=True),
        ),
    ]
