# Generated by Django 2.0 on 2018-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0007_auto_20171221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='excerpt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
