# Generated by Django 2.0 on 2018-01-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0011_auto_20180107_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpageproduct',
            name='bokun_product_hotel_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Product'),
        ),
        migrations.AddField(
            model_name='frontpageproduct',
            name='return_product_hotel_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Product'),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='bluelagoon_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Product'),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='bokun_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Product'),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='photo_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='return_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Product'),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='tagline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
