# Generated by Django 2.0 on 2018-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0012_auto_20180107_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
