# Generated by Django 2.0 on 2018-01-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0014_auto_20180108_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='teenager_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='teenager_price_category_id',
        ),
        migrations.AddField(
            model_name='frontpageproduct',
            name='adult_price_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frontpageproduct',
            name='child_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frontpageproduct',
            name='child_price_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='adult_price',
            field=models.IntegerField(default=0),
        ),
    ]
