# Generated by Django 2.0 on 2018-01-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0015_auto_20180108_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontpageproduct',
            options={'ordering': ['ordering', 'title']},
        ),
        migrations.AddField(
            model_name='frontpageproduct',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
