# Generated by Django 2.0 on 2018-01-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0016_auto_20180108_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontpageproduct',
            old_name='adult_price_return',
            new_name='adult_price_round_trip',
        ),
        migrations.RenameField(
            model_name='frontpageproduct',
            old_name='child_price_return',
            new_name='child_price_round_trip',
        ),
        migrations.RenameField(
            model_name='frontpageproduct',
            old_name='bluelagoon_product',
            new_name='discount_product',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='bokun_product_hotel_connection',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='return_product_hotel_connection',
        ),
    ]
