# Generated by Django 2.0 on 2018-01-10 14:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0017_auto_20180109_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossSaleItem',
            fields=[
                ('bokun_id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('adult_category_id', models.IntegerField(default=0)),
                ('teenager_category_id', models.IntegerField(default=0)),
                ('child_category_id', models.IntegerField(default=0)),
                ('earphone_id', models.IntegerField(default=0)),
                ('jacket_id', models.IntegerField(default=0)),
                ('jacket_question_id', models.IntegerField(default=0)),
                ('boots_id', models.IntegerField(default=0)),
                ('boots_question_id', models.IntegerField(default=0)),
                ('lunch_id', models.IntegerField(default=0)),
                ('lunch_question_id', models.IntegerField(default=0)),
                ('extra_person_id', models.IntegerField(default=0)),
            ],
        ),
    ]
