# Generated by Django 2.0 on 2018-01-11 18:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0019_auto_20180111_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
