# Generated by Django 2.0 on 2018-01-15 16:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0020_auto_20180111_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('incoming_body', jsonfield.fields.JSONField(blank=True, null=True)),
                ('outgoing_body', jsonfield.fields.JSONField(blank=True, null=True)),
                ('bokun_response', models.CharField(blank=True, max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
