# Generated by Django 2.0 on 2018-01-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0021_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestLog',
        ),
    ]
