# Generated by Django 2.0 on 2018-01-15 17:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0022_auto_20180115_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='bokun_response',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
