# Generated by Django 2.0 on 2018-03-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0023_auto_20180115_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='vendor_id',
            field=models.IntegerField(default=942, max_length=10),
            preserve_default=False,
        ),
    ]
