# Generated by Django 2.0 on 2018-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0024_place_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='adult_category_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='boots_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='boots_question_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='child_category_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='earphone_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='extra_person_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='jacket_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='jacket_question_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='lunch_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='lunch_question_id',
        ),
        migrations.RemoveField(
            model_name='crosssaleitem',
            name='teenager_category_id',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='adult_price_round_trip',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='child_price_round_trip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='child_price_category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='child_seat_child_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='child_seat_infant_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_price_category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_baggage_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flight_delay_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flight_delay_question_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='odd_size_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='frontpageproduct',
            name='direction',
            field=models.CharField(choices=[('ANY', 'ANY'), ('KEF-RVK', 'KEF-RVK'), ('RVK-KEF', 'RVK-KEF')], default='ANY', max_length=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='vendor_id',
            field=models.IntegerField(),
        ),
    ]
