# Generated by Django 2.0.3 on 2018-03-28 14:59

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    FrontPageProduct = apps.get_model('bokun_wrapper', 'FrontPageProduct')

    for p in FrontPageProduct.objects.using(schema_editor.connection.alias).all():
        if p.luxury:
            p.kind = 'LUX'
        elif p.private:
            p.kind = 'PRI'
        else:
            p.kind = 'ECO'

        p.save()

def reverse_func(apps, schema_editor):
    FrontPageProduct = apps.get_model('bokun_wrapper', 'FrontPageProduct')

    for p in FrontPageProduct.objects.using(schema_editor.connection.alias).all():
        if p.kind == 'LUX':
            p.luxury = True
            p.private = False
        elif p.kind == 'PRI':
            p.luxury = False
            p.private = True

        p.save()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('bokun_wrapper', '0026_auto_20180327_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpageproduct',
            name='kind',
            field=models.CharField(choices=[('ECO', 'Economy'), ('PRE', 'Premium'), ('PRI', 'Private'), ('LUX', 'Luxury')], db_column='type', db_index=True, default='ECO', max_length=3),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='luxury',
        ),
        migrations.RemoveField(
            model_name='frontpageproduct',
            name='private',
        ),

        # Adding some indexes:
        migrations.AlterField(
            model_name='frontpageproduct',
            name='max_people',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='min_people',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frontpageproduct',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
