# Generated by Django 2.0.3 on 2018-04-04 14:53

import bokun_wrapper.models.activity_property_mixin
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('bokun_wrapper', '0028_frontpageproductbullet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='FrontPageProductBullet',
            new_name='ProductBullet',
        ),
        migrations.RenameModel(
            old_name='FrontPageProduct',
            new_name='Product',
        ),
    ]
