# Generated by Django 2.0.3 on 2018-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0029_auto_20180404_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='product',
            name='tagline_color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('gold', 'Gold')], default='green', max_length=10),
        ),
    ]
