# Generated by Django 2.0.3 on 2018-04-10 12:46

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Product = apps.get_model('bokun_wrapper', 'Product')

    qs = Product.objects.using(schema_editor.connection.alias)

    qs.filter(direction='RVK-KEF').delete()

    for p in qs.all():
        p.activity_inbound = p.bokun_product
        p.activity_outbound = p.return_product or p.bokun_product

        p.save()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('bokun_wrapper', '0030_auto_20180409_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activity_inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bokun_wrapper.Activity', verbose_name='Activity (KEF-RVK)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='activity_inbound_hc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='Activity (KEF-RVK + HC)'),
        ),
        migrations.AddField(
            model_name='product',
            name='activity_outbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bokun_wrapper.Activity', verbose_name='Activity (RVK-KEF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='activity_outbound_hc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='Activity (RVK-KEF + HC)'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_hotel_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='round_trip_discount',
            field=models.CharField(blank=True, max_length=10),
        ),

        migrations.RunPython(forwards_func),

        migrations.RemoveField(
            model_name='product',
            name='bokun_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_product',
        ),

        migrations.AlterField(
            model_name='product',
            name='photo_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
