# Generated by Django 2.0.3 on 2018-04-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0031_auto_20180410_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='round_trip_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='activity_inbound_hc_rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='KEF-RVK + HC (round trip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='activity_inbound_rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='KEF-RVK (round trip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='activity_outbound_hc_rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='RVK-KEF + HC (round trip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='activity_outbound_rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='RVK-KEF (round trip)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bokun_wrapper.Activity', verbose_name='KEF-RVK'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_inbound_hc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='KEF-RVK + HC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_outbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bokun_wrapper.Activity', verbose_name='RVK-KEF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_outbound_hc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bokun_wrapper.Activity', verbose_name='RVK-KEF + HC'),
        ),
    ]
