# Generated by Django 2.0.3 on 2018-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0032_auto_20180410_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
