# Generated by Django 2.0.3 on 2018-06-01 15:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bokun_wrapper', '0035_product_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='bookable_extras',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='json',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photos',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
